### ISSUE TITLE
DialectResolver and wrong hibernate-core jar

### ISSUE THREAD

**Issue by drewwills** [ASU-Capstone/uPortal-Capstone#4]
See this stackoverflow:  http://stackoverflow.com/questions/28444016/how-can-i-force-gradle-to-set-the-same-version-for-two-dependencies

/Users/drewwills/capstone/uPortal/uPortal/uportal-war/src/main/java/org/jasig/portal/utils/jdbc/DelayedValidationQueryResolverImpl.java:32: error: package org.hibernate.service.jdbc.dialect.spi does not exist
import org.hibernate.service.jdbc.dialect.spi.DialectResolver;
                                             ^
/Users/drewwills/capstone/uPortal/uPortal/uportal-war/src/main/java/org/jasig/portal/utils/jdbc/DelayedValidationQueryResolverImpl.java:50: error: cannot find symbol
    private DialectResolver dialectResolver;
            ^

**Comment by npcarney** [comment]
https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html
